version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x86

configuration:
  - Release
  - Debug

before_build:
  - cmd: |-
      mkdir build

build:
  project: dlltest.sln
  verbosity: minimal

#cache:
#  - build

after_build:
  - 7z a dlltest-%Configuration%.zip %Configuration%\

artifacts:
  - path: dlltest-%Configuration%.zip
    name: dlltest
    type: zip

# https://www.appveyor.com/docs/deployment/github/#promoting-selected-tag-to-github-release
deploy:
  # tag: $(APPVEYOR_REPO_TAG_NAME)
  # release: dlltest-v$(appveyor_build_version)
  # description: 'Release description'
  provider: GitHub
  auth_token:
    secure: OGsDOhVHdeWq7ejDbd8R+tj+xxZbkJ6oi9XQJ4RY6WAJHmg+5scgeyEIsrGhXkJ+ 
  artifact: dlltest-%Configuration%.zip
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only